---
- name: Download data file
  become: yes
  become_user: postgres
  get_url: 
    url: http://stat-computing.org/dataexpo/2009/{{ filename }}.bz2
    dest: /tmp/{{ filename }}.bz2
    
- name: Unarchive data file
  become: yes
  become_user: postgres
  shell: bzip2 -d /tmp/{{ filename }}.bz2 

- name: Insert data file to postgres 
  become: yes
  become_user: postgres    
  shell: psql -d FlightData --command "copy public.flightinfo FROM '/tmp/{{ filename }}' DELIMITER ',' CSV HEADER;"