---

- name: Create a PostgreSQL DB server
  hosts: nonsas
  become: yes
  become_user: root
  vars_files:
    - vars.yml

  roles:
  - createdb
  
- name: TS playbook init
  hosts: sasviyaservices
  become: yes
  become_user: root

  tasks:
  - name: Add sas user
    user:
      name: sas
      uid: 10001
      
  - name: Update http proxy
    lineinfile:
      path: /home/sas/.bashrc
      regexp: '^export http_proxy'
      line: 'export http_proxy=http://gelweb.race.sas.com'

  - name: Update https proxy
    lineinfile:
      path: /home/sas/.bashrc
      regexp: '^export https_proxy'
      line: 'export https_proxy=https://gelweb.race.sas.com'

      
- name: Viya Server disk setup
  hosts: sas-all
  become: yes
  become_user: root

  tasks:      
  - name: Install packages
    yum: 
      name: quota
      state: present
      
  - name: Get GEL Disk Prep
    get_url:
      dest: /tmp/diskprep.sh
      url: https://gelweb.race.sas.com/scripts/PSGEL109_001/diskprep.sh
      mode: 744
      owner: root
      group: root
      validate_certs: no
      
  - name: Get GEL Empheral Disk Script
    get_url:
      dest: /usr/sbin/disks_ephemeral.sh
      url: https://gelweb.race.sas.com/scripts/PSGEL109_001/disks_ephemeral.sh
      mode: 744
      owner: root
      group: root
      validate_certs: no
      
  - name: Update GEL script to start disk mount after network
    lineinfile:
      path: /tmp/diskprep.sh
      regexp: '^After'
      insertafter: '^Description'
      line: 'After=network.target'
      
  - name: Execute GEL Disk Prep
    shell: /tmp/diskprep.sh
      
  - name: Execute GEL Empheral Disk Script
    ignore_errors: yes
    shell: /usr/sbin/disks_ephemeral.sh
      
- name: Non SAS Server Setup
  hosts: nonsas
  become: yes
  become_user: root

  tasks:
  - name: Download Viya VA 8.3 Playbook
    get_url:
        dest: /sas/install/SAS_Viya_playbook.tgz
        url: https://gelweb.race.sas.com/mirror/09MZPC/SAS_Viya_playbook.tgz 
        validate_certs: no 
        owner: cloud-user 
        group: cloud-user

  - name: Extract Viya VA 8.3 Playbook
    unarchive:
        src: /sas/install/SAS_Viya_playbook.tgz
        dest: /sas/install
        owner: cloud-user
        group: cloud-user
        
  - name: Update Playbook REPOSITORY_WAREHOUSE
    lineinfile:
        dest: /sas/install/sas_viya_playbook/vars.yml
        regexp: '^(.*)REPOSITORY_WAREHOUSE(.*)$'
        line: 'REPOSITORY_WAREHOUSE: "https://gelweb.race.sas.com/mirror/09MZPC"'
  
  - name: Download Virk for Viya 3.4
    git:
        repo: https://github.com/sassoftware/virk.git
        dest: /sas/ts_playbooks/virk_3.4
        version: viya-3.4
      
- import_playbook: /sas/ts_playbooks/gelopenldap/gel.openldapsetup.yml
  vars: 
    anonbind: true
    OLCROOTPW: Orion123

- name: Viya Playbook Update with LDAP
  hosts: nonsas
  become: yes
  become_user: root
  tasks:
  - name: Push sitedefaults.yml to the playbook
    copy:
      src: /sas/ts_playbooks/gelopenldap/sitedefault.yml
      dest: /sas/install/sas_viya_playbook/roles/consul/files/sitedefault.yml
      owner: cloud-user 
      group: cloud-user
  
  - name: Update Playbook
    replace:
      dest: /sas/install/sas_viya_playbook/roles/consul/files/sitedefault.yml
      regexp: 'groupOfNames'
      replace: 'group'
      backup: yes
        
  - name: Speed up failures
    replace:
      path: /sas/install/sas_viya_playbook/roles/sasdatasvrc-x64_redhat_linux_6-yum/tasks/start.yml
      regexp: 'delay: 10'
      replace: 'delay: 2'
